# Generated by Django 2.0.1 on 2019-09-30 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(max_length=25)),
                ('MOBILE', models.CharField(max_length=25)),
                ('EMAIL', models.CharField(max_length=25)),
                ('COURSE', models.CharField(max_length=25)),
                ('SOURCE', models.CharField(max_length=25)),
                ('LEAD_STATUS', models.CharField(max_length=25)),
                ('DEMO_DATE', models.CharField(max_length=25)),
                ('COUNSIER', models.CharField(max_length=25)),
                ('REMARKS', models.CharField(max_length=25)),
            ],
        ),
    ]
