# Generated by Django 2.0.1 on 2019-10-14 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='demo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(max_length=25)),
                ('COURSE', models.CharField(max_length=25)),
                ('DATE_OF_JOINNING', models.CharField(max_length=25)),
                ('DATE_OF_COMPLETION', models.CharField(max_length=25)),
                ('COURSE_FEE', models.CharField(max_length=25)),
                ('INSTRUCTOR', models.CharField(max_length=25)),
                ('AADHAR_NO', models.CharField(max_length=25)),
                ('MOBILE_NO', models.CharField(max_length=25)),
                ('EMAIL', models.CharField(max_length=25)),
                ('REMARKS', models.CharField(max_length=25)),
            ],
        ),
    ]
